# This is a basic workflow to help you get started with Actions

name: DEVELOP 💡 [Test]

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'verbose'
      tags:
        description: 'Test scenario tags'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 15.x ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Unit-Tests
        run: npm test

      - name: e2e-Tests
        run: npm run test:e2e

      - name: Archive e2e-Test
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: cypress_dist
          path: |
            dist/cypress
